### ISSUE TITLE
Using old version of ts-jest, doesn't support TypeScript 4.x

### ISSUE THREAD

**Issue by Luciden** [vuejs/vue-test-utils-next#1159]
Receiving the warning: 

ts-jest[versions] (WARN) Version 4.5.4 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.

ts-jest is two major versions ahead and supports TypeScript 4.x.

**Comment by cexbrayat** [comment]
Hi @Luciden 

Thank you for opening an issue, but as you can see, this is not a problem with VTU, but with TS & ts-jest
You need to use a more recent ts-jest version, and a compatible TS version with it. Or if you want to use an incompatible TS version, you'll get the warning.

In any case this is not related to VTU, so I'll close this issue.

**Comment by Luciden** [comment]
Hi, thanks for the quick response. Perhaps my issue is poorly worded. ts-jest already supports Typescript 4+. We don't directly use ts-jest. 

The issue is that latest version of vue-test-utils-next is still using version 25.3.1 of ts-test which uses Typescript 3. I'm hoping an upgrade to ts-test 26 or greater will occur. 

We need to use Typescript 4 for Vue 3.2 support so we're stuck with the warnings until vue-test-utils-next updates its version of ts-jest.

**Comment by cexbrayat** [comment]
I think these are two separate things: 

- you have a warning in your project because you must be using ts-jest somewhere (maybe via the Vue CLI? We would need more context to investigate). 
- ts-jest is used to develop VTU, but this should have no impact whatsoever on your code, as it is a dev dependency. Anyway, we have a PR that updates it (see #811 ) but we're stuck until an issue in Vue itself is resolved.
