### ISSUE TITLE
Use with AVA test runner

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vue-test-utils-next#130]
Hi, I'm trying to use the Vue test utils with the AVA test runner.
I didn't use vue-test-utils with Vue 2 yet, but trying to get into the habit for Vue 3.

I found this example of how to mock the the browser variables like `document` for Vue test utils for Vue 2:
https://github.com/eddyerburgh/vue-test-utils-ava-example/blob/master/test/helpers/setup.js

Can someone help me with a minimal setup for `vue-test-utils@2.0.0-alpha.6` or above & ava v3.x?

That original example is quite different from what ava suggests here:
https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md

I wonder what the key differences are and how to best set it up for Vue 3.

**Comment by mesqueeb** [comment]
For me it worked with ava's documentation suggestion:
```
// /test/setup.js
const browserEnv = require('browser-env')
browserEnv(['window', 'document'])
```
this is literally all I have and it seems to work so far.

Can I contribute this to the documentation for Vue test utils alpha for Vue 3 somewhere?

**Comment by lmiller1990** [comment]
Hi! Glad you got this to work. Seems like there is no problem running this with Ava?

Regarding docs - they are in another repo [here](https://github.com/vuejs/vue-test-utils-next-docs/issues/10).

I don't think we should teach people how to configure for every possible test runner in the docs (there are many). But we should definitely provide something generic to the meaning of:

- VTU depends on `document` been available. Recommend JSDom.
- Did you find a way to work with `.vue` files? I am not sure if you need a special loader for Ava, or how it works.

@JessicaSachs is working on the docs for config, [see this issue](https://github.com/vuejs/vue-test-utils-next-docs/issues/10). Maybe you guys can collaborate.

For now I will close this since it looks like there is no actual problem with the library and Ava, it's more a docs related issue.

**Comment by mesqueeb** [comment]
@lmiller1990 it's just that the old vue 2.0 docs of vue-test-utils have documentation on how to set up a variety of test runners, including AVA as well.
Would feel bad for us AVAers if this won't be the case anymore going into 3.0.
Would love to contribute, I'll see how it goes these few weeks then come back.

**Comment by JessicaSachs** [comment]
I think that we should provide the documentation for setting up many test
runners. Vue and other frameworks provide CDN deploy docs and build tooling
docs for specific integrations so... I think we should too.

Thank you for giving us a working solution with AVA :-)
