### ISSUE TITLE
Helpers: nextTick/flushPromises

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next#137]
Follwing up on a discussion on Discord, I wanted to open this issue to gather feedback, experiences, and opinions on how to handle async testing and the usage of `nextTick` and `flushPromises`.

## Differences between `nextTick` and `flushPromises`

I couldn't explain it any better than here: https://github.com/testing-library/react-testing-library/issues/11

## Current state of the art

We're currently returning `nextTick` on several methods.

> I think I was expecting to get away with await wrapper.something() most of the time.

by @cexbrayat. Turns out you might need an indeterminate number of `nextTick` calls to get everything up to date, so you end up using `flushPromises`. Happened the same to me while writing [docs for HTTP requests](https://github.com/vuejs/vue-test-utils-next-docs/pull/26).

Also, there's this question by @JessicaSachs that is worth checking/considering:

> `nextTick` might safely be able to be the default? I don't remember if this prohibits testing of async created hooks (I'm thinking in Vue 2)

### 1. "automagically" call `flushPromises`

The pros is that users have one less thing to worry about – and a thing which is quite low-level.

On the other hand, we might lose the ability to test intermediate states (such as "Loading states") before the promise resolved/rejected. If that's the case, this is a no-go.

### 2. Leave it as is and rely on docs

Pros is that current implementation of VTU-next would work.

Cons is that we all know that explaining something in a documentation does not translate well with "our users will know about this and will take it into account" 😅 

### 3. Create a tool (method? helper?) to wrap `nextTick` and `flushPromises`

Not sure about the _shape_ of that tool, but something along the lines of [waitFor](https://testing-library.com/docs/dom-testing-library/api-async#waitfor). Other alternatives mentioned on Discord are `wrapper.findAsync`.

---

disclaimer: this issue is meant to serve as a place to discuss alternatives. After that, if we reach a consensus, I open to write a proper RFC with the suggested proposal 👍

**Comment by lmiller1990** [comment]
I'm still thinking about this before I formulate my answer. My instinct is the "magic" is not ideal, unless it works 100% of the time.

I'm leaning towards a combination of (2) and (3). We can keep the existing behavior (no breaking change) but include some useful tools or additional methods to make things a bit better. Like how Vue is keeping the options API, but also giving us the Composition API.

I would like to explore something along the lines of `waitFor`. This seems ideal; no breaking change, and a nice, clean abstraction.

I wonder if @JessicaSachs has any ideas - she did a deep dive and explored a bunch of different frameworks as part of a project at Cypress.

**Comment by lmiller1990** [comment]
I will also post this in the Testing channel in Vue land.

**Comment by lmiller1990** [comment]
For some perspective I just did something similar in testing-library and it looks like this:

```js
    await act(async () => {
      fireEvent.click(screen.getByTestId('delete-course'))
      fireEvent.click(await screen.findByText('Erase this course'))
    })
```

It still somewhat leaks implementation details - I needed to know that clicking delete course would trigger an async request.

I could be writing this un-idiomatically for testing-library.

**Comment by victortwc** [comment]
Would it make sense for the wrapper to expose an API so we can await when all promises are flushed?

e.g
```
wrapper.find(".button").trigger("click")

await wrapper.asyncDone() // or await wrapper.stable()

expect(getByText('lorem ipsum')).toBeInTheDocument()

```

**Comment by lmiller1990** [comment]
Interesting - would this basically just be something like

```js
wrapper.asyncDone = async function() {
  return Promise.all([ nextTick, flushPromises ])
}
```

Or something along these lines?

Writing something like this using the [plugin system](https://vuejs.github.io/vue-test-utils-next-docs/guide/plugins.html) would be super easy.

**Comment by lmiller1990** [comment]
I think the simplest solution without making significant changes would just be to re-export a simple `flushPromises` function from VTU. What does everyone think? `import { flushPromises } from '@vue/test-utils`?

Alternatively, we leave it as-is and just document it 🤷‍♂️  I find myself using flush-promises a lot, even in other tests frameworks.  We should include this in the docs, it's mentioned [here](https://vuejs.github.io/vue-test-utils-next-docs/guide/async-suspense.html#a-simple-example-updating-with-trigger) and a few other places.

**Comment by afontcu** [comment]
I'm in favor of reexporting given that `flushPromises` is quite a simple utility function so keeping it in sync won't be a trouble.

**Comment by vincerubinetti** [comment]
Brining this up here rather than creating a new issue since this one seems relevant and seems to include the library authors.

The author of the `msw` library (library for mocking api calls) asserts that `flushPromises` is not a robust way to await external async actions. See this issue here:

https://github.com/mswjs/msw/issues/1163#issuecomment-1067854562

Does anyone have any thoughts about this?

`vue-test-utils` doesn't seem to have an equivalent to `waitFor` from `testing-library/vue`. Is there a workaround or a feature request issue for that?

**Comment by tlebel** [comment]
> Does anyone have any thoughts about this?
> 
> `vue-test-utils` doesn't seem to have an equivalent to `waitFor` from `testing-library/vue`. Is there a workaround or a feature request issue for that?

Interesting question! 

I've never had the need for anything else than await $nextTick or await flushPromise with vue-test-utils – yet I never used `msw`.

First, we must understand that flushPromise works by forcing a macrotask loop cycle that will mandatorily come after the microtask is exhausted – and promises are all executed in the microtask queue. See https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/ 

Then in this case, seems you have to call flushPromise twice with msw because: 1) you flush a promise in msw  2) you flush your promise in mounted hook.

I guess you'd have no flushPromise to do if the call to api was a function called on demand (as opposed to call made in vue lifecycle event), eg.:

```js
async fetch() {
    this.status = "loading";
    try {
      this.blah = await axios.get(...blah...);
      this.status = null;
    } catch (error) {
      this.status = "error";
    }
  },
```

then  
```js
await fetch() 
// no flushPromise required 
expect(...).toBe( .... ) 
```

Given it's in created/mounted hooks, there is probably no escaping the double flushPromise with msw. 

And since vue lifecycle hooks are non-blocking (ie making them async don't block execution of the next life cycle step) I don't see how we could even have a waitFor function since [it _needs_ something to wait for](https://github.com/testing-library/dom-testing-library/blob/1fc17bec5d28e5b58fcdd325d6d2caaff02dfb47/src/wait-for.js#L143-L158). When mounting a vue component, I don't see how this would be possible.

**Comment by tlebel** [comment]
> Interesting. Were you just making an assumption here or did you look at the `msw` code? Because I looked at the compiled `msw` code and did indeed find that every request is essentially behind a `setTimeout(func, 0)` promise, which is essentially a `flushPromises`. So that makes sense.

Assumption, from making a lot of tests with mocks 😅 I sometimes had to call flushPromise twice for similar scenarios. Usually, I try to refactor things to avoid that. Or comment on why I can't! 

> The `msw` author seemed to think needing 2 `flushPromises` was just a coincidence and due to race conditions... but for a race condition, it was extraordinarily consistent (testing on multiple OS's, a variety of new/old machines, 100+ times). Your explanation makes more sense.

I don't think it's not a coincidence 😅

> > [it needs something to wait for](https://github.com/testing-library/dom-testing-library/blob/1fc17bec5d28e5b58fcdd325d6d2caaff02dfb47/src/wait-for.js#L143-L158). When mounting a vue component, I don't see how this would be possible.
> 
> This is a tangent/separate issue, but... I don't get this. To be clear, I'm referring to [these features from `testing-library`](https://testing-library.com/docs/dom-testing-library/api-async/). If they're able to do it with Vue, why can't `vue-test-utils`? Doesn't that feature simply periodically check any kind of assertion and wait for it to be true (with a max timeout of course)?

Testing library have a slightly different philosophy on tests, where the focus is on the DOM (and I agree that makes lot of sense). They do wrapper for common frontend frameworks (eg.: vue, react) that will use [vue-test-utils under the hood](https://github.com/testing-library/vue-testing-library/blob/main/package.json#L48) but expose a different set of tool aimed at inspecting DOM. And when you focus on DOM you don't have a choice but developing those kind utility functions. It's a close step to [e2e testing](https://docs.cypress.io/api/commands/find#Arguments) but without loading all the things in a browser. 

[See philosophy here](https://testing-library.com/docs/guiding-principles): 
> If it relates to rendering components, then it should deal with DOM nodes rather than component instances, and it should not encourage dealing with component instances.

**Comment by vincerubinetti** [comment]
> Testing library have a slightly different philosophy on tests,

> I don't think it's not a coincidence 😅

So... two `flushPromises` working *is* maybe a coincidence, and thus not reliable... and `vue-test-utils` wont implement a function similar to `waitFor` due to philosophy differences...

So what is the recommended solution for this `msw` issue then? Use an arbitrary timeout and hope that `msw` has mocked the api call by then?


FWIW I don't really like the idea of `waitFor` either, as it seems to more tightly couple your test with specific implementation details (e.g. waiting for a div with a certain class name to appear to check that an external api mocking library has done its task).

**Comment by cexbrayat** [comment]
Thanks for the follow-up on this.

The thing is `flushPromises` works well enough, except for msw. Maybe we just need a better `flushPromises`? We just re-export the one provided by `flush-promises` as it does a fairly good job. Except if you want to use msw (which you don't have to, as you can use other libs, or manually mock the API call). 

But are there any alternatives to `flushPromises()` out there that would be better?

**Comment by vincerubinetti** [comment]
Having to call `flushPromises` twice wouldn't be a big deal as long as it was noted, and as long as we're sure that will always work, and isn't just a coincidence/race condition.

It'd be really nice for someone with expert understanding of javascript async/await/event loop (definitely not me) to chime in and concur with `msw` dev's assessment that it's a race condition. I'm personally still not convinced. See my comments above. I'm curious if the issue would still happen if `msw` immediately returned the mocked response on [these lines of code](https://github.com/mswjs/msw/blob/1a7bc36d98e0fa0d0fa1c9da6d7dd40605f239ca/src/utils/handleRequest.ts#L110-L130) instead of always returning it after a `setTimeout 0`.

**Comment by cexbrayat** [comment]
You can probably manually patch msw in your node_modules to experiment if that changes something. 

But I tend to agree that msw probably does something a bit extraordinary as this issue only arises with this library...

**Comment by vincerubinetti** [comment]
You read my mind, was doing that as you commented. And I was able to. The local file I patched was this one:

<img width="230" alt="image" src="https://user-images.githubusercontent.com/8326331/158424527-8359f726-c525-41fe-809c-c78b77e8632a.png">

As the file is, I needed two `flushPromises` for my tests to pass.

After I patched the file to simply return `transformedResponse` immediately, rather than `new Promise(resolve => window.setTimeout(() => resolve(transformedResponse), 0)`, I only needed one `flushPromises` for my tests to pass.

Idk man, this really seems like an `msw` bug (it should not promisify the return if `delay` is `0`), and not a race-condition. Anyone willing to concur?

**Comment by vincerubinetti** [comment]
> EDIT: Important note though – [This Promise](https://github.com/mswjs/msw/blob/1a7bc36d98e0fa0d0fa1c9da6d7dd40605f239ca/src/utils/handleRequest.ts#L110) is certainly there for a reason

Yeah, that's the same promise I'm talking about removing if the delay is 0.

If `msw` cannot remove that without breaking things, then my comment I made before is applicable:

>  It may be that the way msw is implemented is inherently incompatible with flushing promises in this way, and if that's the case it should be noted somewhere.

And I'm begging `msw` and or `vue-test-util` to just make a note of this somewhere that two `flushPromises` are required.

**Comment by vincerubinetti** [comment]
> so there should be no difference whether MSW wraps them in Promises or not

And yet there is a difference. And several people in this thread seem to disagree with you.

> I can totally understand that you don't want to change your implementation

Why though. If it's not satisfying some necessary requirement, this is just stubbornness.

I have to recuse myself from this discussion for my mental health. Good luck to all.

**Comment by kettanaito** [comment]
If you're performing an asynchronous action (and HTTP request _is_ an async action), you must await it regardless if it's delayed by third-party means. The fact that conventional mocking tools introduce a black hole in the place of the request client call, which results in an immediate resolution of any request promise, doesn't mean that's the correct approach. Skipping an event loop cycle is not the way to await asynchronous code, neither it is sensible to assume such code is going to execute at any particular cycle at all. 

> In that case we can amend the documentation to explain that people using msw need 2 flushPromises.

MSW has nothing to do with you requiring two `flushPromises` calls. The function itself is a prerequisite of a third-party tool (`vue-test-utils`) and thus this documentation belongs in that tool, if at all. We work hard to remain library- and framework-agnostic, which includes documentation. We won't include general nature instructions around how to structure your tests or how to await for asynchronous logic—that knowledge is implied and lies outside of the library's scope. 

I'm open to addressing this on the library's side if somebody is able to explain how an internal detail (a Promise we construct) is a responsibility of third-party tools. If we can actually analyze the problem and find the solution, and not a workaround, it will be published in the next release.

**Comment by kettanaito** [comment]
> And yet there is a difference. And several people in this thread seem to disagree with you.

I'm not speaking of behavioral differences. It's clear to me that MSW doesn't play nicely with `vue-test-utils`. I'm referring to a third-party tooling depending on implementation details of other tooling. `vue-test-utils` must not care if a LIBRARY_A wraps a request in a promise, or in a dozen of promises. 

> Why though. If it's not satisfying some necessary requirement, this is just stubbornness.

You must understand my stubbornness then. The code we add to the library is going to be used by hundreds of thousands of people. Yes, I'm particularly stuborn and picky when it comes to any change because I will be maintaining that change for an extended period of time. That alone is a sufficient reason to refuse any workarounds and hacks in order to satisfy particular use cases. That is not how software is built, generally.

**Comment by cexbrayat** [comment]
Maybe my comment was misleading, I was talking about our (VTU) documentation.

As I said, it's ok if you have a strong opinion on how that needs to be handled in your library: the point is the setTimeout with a 0 delay triggers the need for a second flushPromises, and other libs made different choices making it unnecessary. I understand that as a maintainer you don't want to change that and introduce potential breaking changes (it's the same for in VTU). We just need to inform developers using msw with VTU that a workaround exists in our docs. If anyone wants to open a PR on VTU docs, we'll gladly review it 👍

**Comment by kettanaito** [comment]
How can you guarantee that there are no more pending promises on the second tick? In other words, if we introduce an extra Promise on top, now people will need three `flushPromises` calls. I think that is an issue indicating that `flushPromises` either assumes too much or does not fulfill its specification. 

May I ask what benefit `flushPromises` brings compared to something like `waitFor`?

```js
asyncCode()
await waitFor(() => uiElement)
```

Note that this is not a matter of stylistic choice. I find the `waitFor` pattern much beneficial to developers as they are forced to await user-facing logic and not internal logic (like what promises are present, flushed, or pending—things the user, for whom we are writing tests, doesn't care about).

**Comment by cexbrayat** [comment]
We don't guarantee anything: in practice, as most mocking libs have just one promise to return the result, developers rely on flushPromises, and that works fine.  Same if you manually mock: you'll usually use `Promise.resolve()`. The only issues we had about that are people trying to use msw: they just need to know that flushPromises is needed twice in that case, or that they can use other mocking libs. Maybe the practice is different in other ecosystems. The other one I know well is Angular, where you mock API calls in unit tests by using an Observable that returns immediately as well.

`waitFor` is possible and is offered by some higher-level testing libraries that are built on top of VTU, and developers are more than welcome to use them.

But most of us do not need it, as we want to mock API calls without delays and return the response directly, without having to wait for anything because that's not what we're trying to test.

**Comment by lmiller1990** [comment]
We would probably include `waitFor` if Vue Testing Library didn't already do that; I don't think we need to close that intersection. In general, I think Testing Library with the `waitFor` method is probably a more ergonomic alternative to Vue Test Utils for cases like this.

**Comment by jsedanoj** [comment]
This is an old issue, but reach here looking for inspiration... and I got it (thanks folks!) and ended up with this:

```
  test("...", async () => {
    // ...
    await flushPromisesUntil(() =>
      expect(routerPushMock).toHaveBeenCalledWith(`/${anId}?key=${aKey}`),
    );
  });
});

async function flushPromisesUntil(
  expectation: () => void,
  maxRetries: number = 100,
): Promise<void> {
  let numberOfTries: number = 0;
  let lastError: any;
  while (numberOfTries < maxRetries) {
    try {
      expectation();
      return;
    } catch (e) {
      lastError = e;
      numberOfTries++;
      await flushPromises();
    }
  }
  expect.fail(`Expectation never met after ${maxRetries} flushes: ${lastError}`);
}
```

When the test passes, well... it passes. And when it fails, it shows the following error:

```
     → Expectation never met after 100 flushes: AssertionError: expected "spy" to be called with arguments: [ '/an-id?keyX=a-key' ]

Received: 

  1st spy call:

  [
-   "/an-id?keyX=a-key",
+   "/an-id?key=a-key",
  ]


Number of calls: 1

```

I created the flushPromisesUntil() funciton for my case, but I think it admits some resusability for other cases.
