### ISSUE TITLE
$style is undefined when using CSS modules

### ISSUE THREAD

**Issue by frandiox** [vuejs/vue-test-utils-next#179]
Using CSS modules leads to `Property "$style" was accessed during render but is not defined on instance.`.

I guess this should work out of the box with CSS modules or at least document how to use it. A simple workaround to make it pass is:

```js
import { config } from '@vue/test-utils'

config.global.mocks = config.global.mocks || {}
config.global.mocks.$style = {}
```

**Comment by lmiller1990** [comment]
Yep, this is actually not a problem with VTU but `vue-jest` not handling `$style`. I have not ported that part of `vue-jest` yet, as you can see those tests are [commented out](https://github.com/vuejs/vue-jest/blob/next/e2e/__projects__/style/test.js) in the `next` branch.

Since this is not a problem here, but `vue-jest`, I will close this. If you would like you can add a note to the README in this repo (or vue-next).

Issue to follow this up: https://github.com/vuejs/vue-jest/issues/268
