### ISSUE TITLE
A way to mock router and store that are used in setup()

### ISSUE THREAD

**Issue by AnnaYuS** [vuejs/vue-test-utils-next#196]
I'm using router and store inside `setup()`.  
```
setup () {
    const store = useStore()
    const router = useRouter()

	async function save () {
		...
		await store.dispatch('save')
		router.push({...})
}
```

Mocking the store this way doesn't seem to work, I'm getting the error:  `TypeError: Cannot read property 'dispatch' of undefined`
 
```
const actions = {
      save: jest.fn(() => {
        return Promise.resolve({ data: '' })
      })
    }

const $store = createStore({
            actions: actions
    })

const wrapper = shallowMount(Component, {
      global: {
        mocks: {
          $store
        }
      }
    })
```

Is there a way to mock the store and the router?

**Comment by lmiller1990** [comment]
`mocks` is only used for things on `this`, such as `this.$store` and `this.$router`. It won't work for the composition API.

VTU won't be able to support mocking a specific module function (such as `useStore` from Vuex) - this is something you will need to use your test runner's mocking functionality for.

If you are using Jest you can do it like this:

```js
const mockDispatch = jest.fn()

jest.mock('vuex', () => ({
  useStore: () => {
    return {
      dispatch: mockDispatch
    } 
  }
}))
```

So we just mocked out the part of Vuex that we want to test. Then you could just do `expect(mockDispatch).toHaveBeenCalledWith(......)`.

Example of mocking Vue router from my course on Vue 3 + VTU can be seen here https://github.com/lmiller1990/vuejs-composition-course/blob/edd06e88f8d869de162b6059eb843355a91082fb/src/NewPost.spec.ts#L8.

**Comment by AnnaYuS** [comment]
Thanks for your help!

Using `global.provide` also worked for mocking vuex store like in the example from your course:

```
	const store = createStore()
    const wrapper = mount(NewPost, {
      global: {
        provide: {
          store
        }
      }
    })
```

Probably because `useStore` from `vuex` uses `inject`.

**Comment by lmiller1990** [comment]
Yep, that would work fine too. Basically when you do `app.use(store)` it is doing `provide` "under the hood". So you just replicated that here.

Technically this is not *mocking* the store - it's using a real store. Mocking the store is when you use an entirely fake one. I like to use a real one when I can, so that way if I delete an action or something like that, the test will fail. A lot of people prefer to mock their Vuex store - which ever makes you more confident.

I will close this one off for now, but I should update [the example in docs](https://vuejs.github.io/vue-test-utils-next-docs/guide/vuex.html#testing-with-a-real-vuex-store) to make it clear `$mocks` won't work with the composition API.
