### ISSUE TITLE
ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by Styx11** [vuejs/vue-test-utils-next#234]
Hi! Today I'm using karma + ( mocha, chai ) unit test in Vue 3, but I've got a reference issue: ` ReferenceError: Vue is not defined`

I think it's not a configuration problem and `Vue` global object should be removed in Vue 3, so maybe is VTU itself:
```shell
  ReferenceError: Vue is not defined
      at Object.<anonymous> (webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.browser.js:2407:5 <- specs/Hello.spec.js:13561:7)
      at Object.<anonymous> (specs/Hello.spec.js:13563:30)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:1 <- specs/Hello.spec.js:20:30)
      at Module.<anonymous> (webpack:///test/unit/specs/Hello.spec.js:1:1 <- specs/Hello.spec.js:95:73)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:1 <- specs/Hello.spec.js:20:30)
      at webpack:///webpack/bootstrap:83:1 <- specs/Hello.spec.js:84:18
      at specs/Hello.spec.js:87:10
```
for more details you can check out and clone my repo (you may ignore the `.yarnrc` by the way): https://github.com/Styx11/vue3-boilerplate/tree/v0.0.1

Thanks : )

**Comment by lmiller1990** [comment]
It is reading `node_modules/@vue/test-utils/dist/vue-test-utils.browser.js`, which is the iife build (eg, used via a `<script`> tag). It expects Vue to be globally available, so something like

```
<script src="https://unpkg.com/vue@next"></script>
```

You can see it on the last line:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/19196536/97938670-b1989480-1dcd-11eb-96fc-bd5828182c24.png">

(It also expected Vue Compiler DOM to be globally available).

I am not sure how this karma setup is supposed to work - is it supposed to bundle everything with webpack *then* execute the tests? Are the tests supposed to be bundled?

**Comment by lmiller1990** [comment]
Going to need more info - happy to reopen if it turns out this is a bug in VTU and not config, at this point it is not clear.

**Comment by madpilot78** [comment]
Hi,

I was migrating a Vue3 project from jest 27 to jest 28 and was seeing this error. I stumbled in this bug report, which moved me in the right direction. I decided to post my solution here in case someone else ends up here.

It turns out to be a non obvious configuration issue.

Obviously in this vue project I'm using the `jest-environment-jsdom`, which by default sets:

```
customExportConditions = ['browser'];
```

This is what causes the test suite to try to load the iife build, but the tests are really running in node, so the "fix" was to put this in my jest configuration (via `package.json`):

```
    "testEnvironment": "jsdom",
    "testEnvironmentOptions": {
      "customExportConditions": [
        "node",
        "node-addons"
      ]
    },
```

Changing the customExportConditions makes it load the correct file and everything now works.

Hope this information can be useful to others!

**Comment by gwvt** [comment]
Thank you @madpilot78!!

**Comment by kevinmims** [comment]
@madpilot78 Thank you for posting this "fix".  The question is how did this "change" get into the package without notification?

**Comment by madpilot78** [comment]
@kevinmims Looks like this is due to changes in jest, specifically to `jest-environment-jsdom`.

The file to look should be https://github.com/facebook/jest/blob/main/packages/jest-environment-jsdom/src/index.ts

https://github.com/facebook/jest/commit/c8c32d3704469557ecfc3d4a9e81002f11e2075d this recent change could be the main cause.

**Comment by madpilot78** [comment]
Actually this one https://github.com/facebook/jest/commit/432dfb686e7586a9ce89c086b261eab432424960 looks a better candidate.
