### ISSUE TITLE
how can i test v-mode 

### ISSUE THREAD

**Issue by ganlinzhen** [vuejs/vue-test-utils-next#241]
vue3.0 do not has $on, how to process v-model

**Comment by lmiller1990** [comment]
It's not clear what you are trying to do. Please post some code to show what you would like to do.

Closing this because 1) you haven't shown an example of what you are trying to do and 2) this doesn't seem like a bug, more like a question.

You can update the value of something like `<input v-model="foo" />` with `find('input').setValue('asdf')`. You can check if the correct event is emitted (eg `update:modelValue`) with `wrapper.emitted()`.
