### ISSUE TITLE
Undefined TypeError when using inject in setup api

### ISSUE THREAD

**Issue by Mootook** [vuejs/vue-test-utils-next#256]
Hello, I have been trying to setup a test system for a new app my team is working on in Vue3. I set it up using
[vue/cli-plugin-unit-jest](https://www.npmjs.com/package/@vue/cli-plugin-unit-jest) and am also using [vue-class-store](https://github.com/davestewart/vue-class-store) for state management which provides a state class at the app root and is subsequently injected in any children that need it.
However, running any unit test on a component that injects the store gives `TypeError: Cannot read property 'child' of undefined`. Child being the nested key which is accessed by the comopnent. The app runs fine.

I've setup a small [demo](https://github.com/Mootook/vue-store-jest-ex) to show, and I can also post the jest/babel configs from the actual project if those would be helpful as well.

I've tried:
- Different ways of injecting/providing the class store in the components
- Passing in a false store in the provide parameter of the vue-jest mount api
- Passing in app root as parentComponent option of the tested component

I'm also quite new to testing and would really appreciate any help or insight into the issue.
Thank you.

**Comment by lmiller1990** [comment]
You are providing your store in `App.vue` - but you do not provide a store in your tests anywhere. That's the problem.

For this we provide the [`global.provide`](https://vue-test-utils.vuejs.org/v2/api/#global-provide) mounting option.

I had to export a few methods from your `src/store.js` file. I then was able to write this test:

```js
import { mount } from '@vue/test-utils'
import HelloWorld from '@/components/HelloWorld.vue'
import { createStore, StoreSymbol } from '@/store'

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', async () => {
    const msg = 'new message'
    const wrapper = mount(HelloWorld, {
      global: {
        provide: {
          [StoreSymbol]: createStore()
        }
      },
      props: { msg }
    })
    expect(wrapper.text()).toMatch(msg)
    expect(wrapper.html()).toContain('Counter 0')
    await wrapper.find('button').trigger('click')
    expect(wrapper.html()).toContain('Counter 1')
  })
})
```

Hopefully this gets you started in the right direction. Since there is no bug to speak of, I will close this issue. Let me know if you have any more problems, I can try and help out.
