### ISSUE TITLE
Better way to handle `emitted` internally

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next#292]
There is a hook in core for devtools. We could use that? The close integration is likely going to be better, less buggy, and make things more reliable. https://github.com/vuejs/vue-next/blob/ee266af42ab8f97011c6736aa82409a35c402e94/packages/runtime-core/src/devtools.ts#L82

**Comment by afontcu** [comment]
(_I've added "internally" to the title because I first thought you were about to present a better `emitted()` API 😅_)

**Comment by cuixiaorui** [comment]
I did some research on devtools

It turns out that if you use devtools, it's not that different from what we have now

Devtools is used for the [Vue DevTools](https://github.com/vuejs/vue-devtools/)

This devtools is dependent on windows.__vue_devtools_global_hook__ to inject devtools

If we use devtools to implement emitted, it needs to deal with two conditional branches
- windows.__vue_devtools_global_hook__ if it has a value (already injected by Vue devtools)
  - We need to wrap windows.__vue_devtools_global_hook__. emit this function
- windows.__vue_devtools_global_hook__ does not have a value
  - We need to build our own devTools and inject it

Or maybe I didn't think it would be better than the current one :)

**Comment by lmiller1990** [comment]
Thanks @cuixiaorui, that is useful info. There are some edge cases we miss with the current approach. For example:

```js
const C = {
  setup(props, { emit }) {
    emit('foo')
  }
}
```

We cannot capture this `emit` since we install a emit listener mixin on the `beforeCreate` hook, and `setup` is called prior. Would using the devtools hook fix this bug?

**Comment by cuixiaorui** [comment]
Uh-oh, I see

I gave it a try, and devtools can solve this problem

I will submit a PR later
