### ISSUE TITLE
`input.trigger('compositionstart')` not work

### ISSUE THREAD

**Issue by danranVm** [vuejs/vue-test-utils-next#391]
The code works in `rc0`, but fails in `rc1`.

```ts
  test('v-model work', async () => {
    const valueRef = ref('init value')
    const wrapper = mount({
      components: { IxInput },
      template: `<ix-input v-model:value="valueRef" />`,
      setup() {
        return { valueRef }
      },
    })
    const input = wrapper.find('input')

    expect(input.element.value).toBe('init value')

    await input.setValue('input setValue')

    expect(valueRef.value).toBe('input setValue')

    valueRef.value = 'valueRef change'

    await nextTick()

    expect(input.element.value).toBe('valueRef change')

    input.element.value = '使用拼音'
    await input.trigger('compositionstart')

    expect(wrapper.emitted()).toHaveProperty('compositionStart')
    expect(valueRef.value).toBe('valueRef change')

    await input.trigger('input')

    expect(wrapper.emitted()).toHaveProperty('input')
    expect(valueRef.value).toBe('valueRef change')

    await input.trigger('compositionend')

    expect(wrapper.emitted()).toHaveProperty('compositionEnd')
    expect(valueRef.value).toBe('使用拼音')
  })
```

repo: https://github.com/IduxFE/idux

**Comment by lmiller1990** [comment]
Uh oh... regression.

**Comment by lmiller1990** [comment]
Maybe this commit? https://github.com/vuejs/vue-test-utils-next/pull/354

**Comment by aethr** [comment]
@lmiller1990 interesting, at first I was inclined to agree, in a Vue app in the browser the events emitted by inner components/elements should not escape the component, and we would expect this to fail:

```js
const input = wrapper.find('input')    
await input.trigger('input')
expect(wrapper.emitted()).toHaveProperty('input')
```
But this would pass:
```js
const input = wrapper.find('input')    
await input.trigger('input')
expect(input.emitted()).toHaveProperty('input')
```

However, in this case since the `<ix-input>` component is the root element and `inheritAttr` isn't `false`, would events emitted by `<ix-input>` be emitted? I'm actually not sure. Would be worth making a repro in the browser to check.

**Comment by lmiller1990** [comment]
Hm. Looking that `<ix-input />` it is basically like this:

```ts
export const useCommonBindings = () => {
  const { emit } = getCurrentInstance()!
  const onCompositionStart = (evt) => {
    emit('compositionStart', evt)
  }
  return { onCompositionStart }
}
```

```html
<input @compositionstart="onCompositionStart" /> 
const { onCompositionStart } = useCommonBindings(props, inputConfig, inputRef)
```

Further reduced:

```html
<input @compositionstart="(evt) => emit('compositionStart, evt)" /> 
```

But the test does `await input.trigger('compositionstart')`. I *don't* think this is valid - `trigger` is supposed to be simulating user inputs, and a user cannot do `compositionStart`. `trigger` only worked with DOM events in Test Utils v1 - so I think your fix is actually valid.

EDIT: wtf `compositionStart` is actually a [real DOM event](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event). The more you know.

**Comment by aethr** [comment]
I see the problem now.

I think the issue is the difference between DOM events and Vue component custom events. DOM events bubble up through parent elements in the DOM until propagation is stopped. Vue events occur on the component and no further unless they're manually re-emitted by the parent.

I made a code sandbox to illustrate: https://codesandbox.io/s/amazing-knuth-hm91e?file=/src/App.vue

In this example a native event (`input`) can be listened for at the grand-parent `App`, but custom event `update:modelValue` doesn't bubble outside of `Parent`.

#354 doesn't handle native DOM events properly in this regard, I naively assumed the VTU `emitted` was for component events but obviously it needs to provide native events as well. My bad!

I do think whatever solution VTU adopts needs to treat both event types the way they occur in the browser, `Wrapper.emitted()` should capture all native events that bubbled out to that component, but only custom events that were emitted by the wrapper's direct component. I'm certain this was the old behaviour as we have an entire test suite that was written against that assumption.

**Comment by lmiller1990** [comment]
I think you are correct regarding custom vs native.

Do you think it would be difficult to make this fix? Note we have the [dom-event-types](https://github.com/vuejs/vue-test-utils-next/blob/a5f9a30d2a076048647f13c5895c154f112e573d/package.json#L27) lib that may help with thisl

**Comment by aethr** [comment]
Well, after a brief investigation it appears the Vue devtools hooks only captures custom events.

**Comment by aethr** [comment]
I'm going to try adding a native event listener to the element of each `Wrapper` to capture native events. I'll try and have a draft PR up tonight.

**Comment by lmiller1990** [comment]
Ohhhh true, why would it capture non custom events? Interesting.

I think we can just do what we did before for *native* events. [See this file](https://github.com/vuejs/vue-test-utils-next/blob/v2.0.0-beta.14/src/emitMixin.ts). We would need to check if it's an native event or not (using dom-event-types).

The reason we moved to using devtools was to be able to capture events from `setup` - since the eventMixin is not added until beforeCreate. That said, you cannot possibly emit a DOM event in `setup`, so I think we can do a combo approach - devtools hook for custom, mixin for native.

Thoughts? If you have something better, by all means go with that. But this approach is definitely confirmed to work for native events.

**Comment by aethr** [comment]
I made a PR that I think should add native events to `emitted` but it's pretty ugly, feel free to close if you think the mixin approach is more solid. It's late here so I can't take it any further tonight. :)

**Comment by lmiller1990** [comment]
I found a fix - but @danranVm I think you will need to change your assertion to `toHaveProperty('compositionstart')` when we fix this - native events will bubble, but non native ones won't - the native event is `compositionstart`, not `compositionStart`.

I will ping you again when this is fixed and released. Probably rc.2 will be this weekend. Thanks!

**Comment by danranVm** [comment]
@lmiller1990 Okay, I will try again in rc.2. Thanks!

**Comment by lmiller1990** [comment]
@danranVm it's out now, please try rc.2 Note you will likely need `compositionstart` not `compositionStart` for your event name.

**Comment by danranVm** [comment]
> @danranVm it's out now, please try rc.2 Note you will likely need `compositionstart` not `compositionStart` for your event name.

Tks, after modifying according to your suggestion, it can work.
