### ISSUE TITLE
shallowMount weird behaviour with repeating component stubs in snapshot

### ISSUE THREAD

**Issue by LorinIonita** [vuejs/vue-test-utils-next#530]
I haven't seen an issue like this and I'm not sure if this is an issue on my end but there's a weird behaviour when trying to shallow mount a component with multiple repeating components. `ai-btn` and `ai-icon` are added as global components in the mount.

This is the component:

```
<template lang="pug">
  .ai-simple-pagination
    ai-btn.ai-simple-pagination__arrow-button.left(
      variant="label",
      @click="goBack",
      :disabled="!hasPrev"
    )
      ai-icon.ai-simple-pagination__icon(
        icon="arrow-small-left",
        width="30",
        height="30"
      )
    ai-btn.ai-simple-pagination__arrow-button.right(
      variant="label",
      @click="goForward",
      :disabled="!hasNext"
    )
      ai-icon.ai-simple-pagination__icon(
        icon="arrow-small-right",
        width="30",
        height="30"
      )
</template>

<script lang="ts">
import {
  ref,
  PropType,
  defineComponent,
} from 'vue';

export default defineComponent({
  name: 'AiSimplePagination',
  props: {
    value: {
      type: Number,
      default: 1,
    },
    onChange: {
      type: Function as PropType<(val: number) => void>,
      required: true,
    },
    hasPrev: {
      type: Boolean,
      required: true,
    },
    hasNext: {
      type: Boolean,
      required: true,
    },
  },
  setup(props) {
    const model = ref<number>(props.value);

    const goForward = () => {
      model.value += 1;
      props.onChange(model.value);
    };

    const goBack = () => {
      model.value -= 1;
      props.onChange(model.value);
    };

    return {
      model,
      props,
      goForward,
      goBack,
    };
  },
});
</script>
```

When mounting it with `shallowMount` and expecting it to match the snapshot, the snapshot looks like this:

```
<div
  class="ai-simple-pagination"
>
  <ai-btn-stub
    class="ai-simple-pagination__arrow-button left"
    disabled="true"
    variant="label"
  >
    <ai-icon-stub
      class="ai-simple-pagination__icon"
      height="30"
      icon="arrow-small-left"
      width="30"
    />
  </ai-btn-stub>
  <ai-btn-stub
    class="ai-simple-pagination__arrow-button left ai-simple-pagination__arrow-button right"
    disabled="false"
    variant="label"
  >
    <ai-icon-stub
      class="ai-simple-pagination__icon"
      height="30"
      icon="arrow-small-left"
      width="30"
    />
  </ai-btn-stub>
</div>
```

As you can see the second `ai-btn-stub` has the classes of the first one also and the second `ai-icon-stub` has the icon from the left one instead of it's own.

**Comment by vsergiu93** [comment]
Hello, 

I forked this so I can write a [test case]( https://github.com/vsergiu93/vue-test-utils-next/blob/052783165d3b69418b1ee824f14f7679aa9208f9/tests/shallowMount.spec.ts#L104) which reproduces the above behavior when shallow mounting a component.

**Comment by yakobe** [comment]
It seems the cause is [this line](https://github.com/vuejs/vue-test-utils-next/pull/453/commits/7016c594b5392db71510dca42af188c153f6d512#diff-840c8e77baceaebec1b759efa8bbb8505149fbd81c64bb120801388b66d839c4R173) on #453. Its seems to break the rendering of attributes in the html.

Here is an updated version of the test that shows it breaking: https://github.com/yakobe/vue-test-utils-next/commit/3283eeeabaa7fb6da81be6b611e18c44f0e4409b

**Comment by lmiller1990** [comment]
So #453 introduced the regression?

We might just want to revert it. The rationale was to allow:

```js
it('non-shallow mount', async () => {
        const wrapper = mount(OuterComponent, {
            shallow: false
        });

        const innerComponent = wrapper.getComponent(InnerComponent);
        await wrapper.find('button').trigger('click');
        expect(innerComponent.props()).toHaveProperty('text', 'new text');
    });
```

To work, but it looks like this might introduce problems by caching the stub. Instead we would just require users to re-run `getComponent` to get the updated values and whatnot. 🤔

**Comment by senaria** [comment]
Hey I ran into the same issue. We would like to have it fixed. Therefore could you revert it?

**Comment by lmiller1990** [comment]
The problem is either way, we have a breaking change from V1 - if we revert it, https://github.com/vuejs/vue-test-utils-next/issues/362 is going to a problem again.

In a real browser, if you do:

```js
const foo = document.querySelector("#foo")
foo.textContent = "bar"
console.log(foo.textContent) // it's "bar"
```

So the code in https://github.com/vuejs/vue-test-utils-next/issues/362 makes Test Utils stubs closer to the generally expected behavior in a browser - reverting this seems like a step backwards, and a significant breaking change from VTU v1 -> VTU v2.

I am not sure on the best way to handle this - ideally we want to have both of these behaviors, we should not need to choose one breaking change over another.

**Comment by yakobe** [comment]
The problem is that all snapshots that use the same component more than once break with that change too. It's not just when you query for prop values. That seems like a more serious break 😬. Literally half my test suites on multiple projects fails if I upgrade past RC3. 

I would like to try to help solve the problem, but my knowledge how things work in this code base is very limited. Perhaps the problem is the caching you mentioned above? Maybe it's worth removing it and seeing if both features work again? If so we can add the test to ensure the features and work out how improve performance later (I'm assuming that the caching is only for performance).

**Comment by lmiller1990** [comment]
The caching was adding in [this PR](https://github.com/vuejs/vue-test-utils-next/pull/453) for the specific reason to make it so you don't need call `getComponent`  again to get the updated version, removing it will definitely break the original bug it fixed.

While I understand snapshot + `shallowMount` is somewhat common in the Vue testing community, it breaks a lot of well established practices around testing. A snapshot of a `shallowMount` component is basically an assertion against the internal details of Vue Test Utils - it provides little to no validation that your component actually behaves how it should. Are you able to share the projects/test? Happy to provide some feedback/alternative testing strategies.

It would be great to fix this,  but we can't do so if it means reverting real bug fixes (like the one described in [this issue](https://github.com/vuejs/vue-test-utils-next/issues/362) because of a test depending on an implementation detail.

A potential fix that would allow us to support both behaviors might be to only use the cached stubs when using `getComponent` or `findComponent`. Even then, I'd still recommend against `shallowMount` + snapshots - they do not provide any validation outside of notifying you that an implementation detail changed, which is not something you should care about when testing.

Opinions aside, we can leave this open until we fix it. Let's explore some `get/findComponent` specific behavior - if we add the example reproduction but the OP, we have a solid test suite to guide us.

**Comment by mariusheine** [comment]
We ran into the same problem. We don't check against a snapshot but we check if attributes have specific values so something like 

```
// (pseudo-code with example from above)
wrapper.findAll("ai-icon")[0].attributes("icon").toBe("left-icon");
wrapper.findAll("ai-icon")[1].attributes("icon").toBe("right-icon");
```

where the second assertion would fail due to the caching.

Shallowing makes sense in those cases where the ai-icon component has its own tests. If we use mount it might cause issues due to mocking or other stuff at any later point.

So do you have any ideas or plans if this can be fixed?

**Comment by yakobe** [comment]
@mariusheine that's a similar situation to me. I'm rarely using snapshots anymore, but I have many scenarios where I use shallow mounts to reduce side effects and test for attributes/props on them.

**Comment by lmiller1990** [comment]
> So do you have any ideas or plans if this can be fixed

@mariusheine it's a bug so we should definitely fix it. I did not get to explore this deeply yet. Happy to either help out if someone has the time to, or do it when I have the time. I don't have an idea on how to fix it immediately, my approach is normally to add the test case I want to pass into this code base, then just run the tests in watch mode and modify code until everything passes.

> Should shallow mount just not exist if it's not meant to be used? Or for what scenarios should we use it if attributes/props are not good to check against? (Honest question with absolutely no malicious intent 😬. I'm pretty new to the js/ts world).

@yakobe I generally don't like to use shallow mount for the reasons outlined above, especially with a snapshot - I don't think it's useful to know a specific DOM snapshot, I find more value in knowing the component behaves correctly (eg: if I click on this button, does the component update how I expect, etc). I find these tests fail a lot during refactoring, even if the code still works fine. I think good tests should be resilient to a major refactor.

Opinions aside, we should still make sure that everything behaves as you'd expect. Right now the shallow snapshot output is wrong, so we should fix it. I am guessing we just need some specific logic for `findComponent` and `getComponent` 🤔 we know that this *was* working before, so we should be able to come up with a combination of code that satisfies all use cases.

**Comment by yakobe** [comment]
@lmiller1990 Sounds good! I would love to help. 

> my approach is normally to add the test case I want to pass into this code base, then just run the tests in watch mode and modify code until everything passes.

My change in https://github.com/yakobe/vue-test-utils-next/commit/3283eeeabaa7fb6da81be6b611e18c44f0e4409b extends the existing tests with an extra check for this bug. It obviously fails at the moment but I guess we can fiddle with the code until everything passes 😄.

Unfortunately I'm a noob at contributing to OSS. I have many years of non-OSS, but on long running projects so I dont have a "flow" yet for contributing quickly. With a bit of luck I will find some time to take a look soon. In the mean time, let me know if there's anything else i can do to help.

**Comment by lmiller1990** [comment]
The flow is pretty much the same as non OSS.

- identify problem (we did that here)
- fork and clone this repo (you did that [here](https://github.com/yakobe/vue-test-utils-next/commit/3283eeeabaa7fb6da81be6b611e18c44f0e4409b)
- add a test to reproduce the current problem, a more minimal version of the test in the OP (also you did that [here](https://github.com/yakobe/vue-test-utils-next/commit/3283eeeabaa7fb6da81be6b611e18c44f0e4409b))
- fix the problem
- push to your repo 
- make a PR
- 🍻

**Comment by YutamaKotaro** [comment]
I created PR #610 for this problem, and want to resolve this issue too ...!!
However it has a little problem, what do you think of it ??

**Comment by lmiller1990** [comment]
@YutamaKotaro wow, great!

what is the "little problem" you are referring to?

**Comment by YutamaKotaro** [comment]
@lmiller1990 
As you already gave me comments, what I meant was the orders of attributes and props.
https://github.com/vuejs/vue-test-utils-next/pull/610#discussion_r637392308
So, there is no big problem. Thanks for your kindly comments !!

**Comment by lmiller1990** [comment]
Hello everyone. @YutamaKotaro fixed this problem. I will do a release soon with the fix.
