### ISSUE TITLE
In MountingOptions is missing computed property

### ISSUE THREAD

**Issue by mariosh346** [vuejs/vue-test-utils-next#545]
In vue-test-utils v.1.1.2 there was a computed option in MountingOptions. Is this removed? 
Is there a way to mock computed properties?

**Comment by afontcu** [comment]
Hi! 👋  I might be wrong, but I'm not entirely sure VTU 1 provides a `computed` option 🤔 Could you share a use case where mocking a computed property is necessary? I'd say a sensible approach would be to pass down the right props / interact with the component until the computed has the right value.

**Comment by mariosh346** [comment]
The most times that this is needed is to mock a complex computed and test it separately. 
 https://github.com/vuejs/vue-test-utils/issues/331 Here you can see that they propose the use of computed option instead of setComputed

**Comment by lmiller1990** [comment]
We have a computed mounting option a looooong time ago, not in 1.1.2, though. It was removed for the same reason `methods` was removed.

Since computed properties are just derived from other sources (like `data`) you can generally use the `data` mounting option to accomplish the same thing.

If you want additional guidance, please post an example of the test you'd like to write. `computed` as a mounting option was deprecated a long time ago in v1 - the goal of v2 is to match VTU v1's API, so we won't add additional features here that are not supported in v1 at this point in time.

**Comment by doutatsu** [comment]
This is quite a shame this was removed. Mocking computed properties made it a lot easier to use a real VueX store, but the stubbing out a specific getter for example, for a specific test:

```js
      beforeEach(() => {
        store = createStore({
          modules: {
            lists: {
              namespaced: true,
              state: lists.state,
              mutations: lists.mutations,
              getters: lists.getters,
            },
          },
        });

        actions = shallowMount(TheDashboardListActions, {
          computed: { selectionModeActive: () => true },
          global: {
            plugins: [store],
            mocks: {
              $grid: { lg: false },
              $screen: { touch: true },
            },
          },
        });
      });
```
