### ISSUE TITLE
findAllComponents() returning the same component twice?

### ISSUE THREAD

**Issue by Giwayume** [vuejs/vue-test-utils-next#689]
Is there a reproduction template for https://codesandbox.io? I'm having trouble finding one.

My component looks something like this:
```
<template>
    <component1 v-for="item in array" :key="item+ '_item'">
        <component2 data-some-attr="attrvalue" />
    </component1>
</template>
<script>
return {
    data() {
        return {
            array: ['foo']
        };
    }
};
</script>
```

Test is trying to retrieve all component instances by the custom attribute:
```
it('test', () => {
    const wrapper = mount(MyComponent);
    const components = wrapper.findAllComponents('[data-some-attr="attrvalue"]');
    expect(components.length).toBe(1);
});
```

It fails on the length assertion, appears to return the same component twice, even though array controlling the loop has 1 item.

If this problem is not familiar to you, I'd like to know if there's an easy reproduction template so I can sort this out.

**Comment by lmiller1990** [comment]
I could not reproduce this: https://github.com/vuejs/vue-test-utils-next/compare/issue-689?expand=1

I don't think we have CSB yet. You could fork this repo, and reproduce it there - that'd be ideal, since then if there is a bug, we have the failing test case. I usually put components for reproductions inside of https://github.com/vuejs/vue-test-utils-next/tree/master/tests/components. You can use `.vue` files, or inline render functions like I did in my example - both are fine.

**Comment by xanf** [comment]
@lmiller1990 here we go with reproduction

```js
  it('finds components - demo', () => {
    const CompA = {
      template: '<div>A</div>' 
    }
    const CompB = {
      components: { CompA },
      template: '<comp-a />'
    }
    const RootComponent = {
      components: { CompB },
      template: '<div><comp-b class="foo" /></div>'
    }

    const wrapper = mount(RootComponent);
    // will return 2
    expect(wrapper.findAllComponents('.foo')).toHaveLength(1)
```

Frankly speaking, I'm not sure what is **correct** answer here
VTU v1 [previously returned](https://codesandbox.io/s/hopeful-chaplygin-y8c3s?file=/src/App.test.js) 1 for this scenario, returning top matching node - CompB. Why previously? Because usage of `findAllComponents` with DOM selector was removed in v1

While it might look reasonable to have "2" returned, the problem is, that this "2" might become "3" for example - consider `CompA` being refactored to have one more level of nesting. This is bad, because (for example) CompB might be some library component and we definitely do not want to rely our tests on implementation details of library and I definitely do not want `@vue/test-utils` to allow creating such fragile tests.

IMO it might be great to remove ability to find components by DOM selector in the same way it was done in VTU v1
In my opinion selecting Vue component by DOM selector

**Comment by lmiller1990** [comment]
Right - I agree, we should not support finding components via CSS selector. This was deprecated, and should not have been implemented here in the first place, right?

**Comment by Giwayume** [comment]
I don't agree, cause all my unit tests are written using CSS selectors. What if I'm testing a 3rd party library component where I do not have the ability to modify the source code?

How does this behavior compare to v1 where it wasn't broken?

**Comment by xanf** [comment]
@Giwayume I can't say previous behavior (in VTU v1) was not broken - since multiple components can have same `$el` - it is a tough philosophical discussion what is **correct** behavior here.

> What if I'm testing a 3rd party library component where I do not have the ability to modify the source code?

I believe (please note - I'm not a member of VTU team) that if you're relying on retrieving **components** from inside of 3rd party component HTML - you're testing implementation details of 3rd party component, which is definitely not the way VTU should encourage people to do.

**Comment by xanf** [comment]
@Giwayume I can't say previous behavior (in VTU v1) was not broken - since multiple components can have same `$el` - it is a tough philosophical discussion what is **correct** behavior here.

> What if I'm testing a 3rd party library component where I do not have the ability to modify the source code?

I believe (please note - I'm not a member of VTU team) that if you're relying on retrieving **components** from inside of 3rd party component HTML - you're testing implementation details of 3rd party component, which is definitely not the way VTU should encourage people to do.

**Comment by Giwayume** [comment]
It's not so much that I'm testing the functionality of the 3rd party components, but using CSS selectors to interact with them is required in order to test our UI that is built with them.

**Comment by lmiller1990** [comment]
I think `findComponent` should match the current  V1 behavior, which is not to support CSS selectors iirc. It currently does (and is documented, as well), so removing this will be a breaking change. We are pre 2.0, so we can make a breaking change, but we should make sure there is a migration path.

I don't fully understand how to use CSS selectors with a third party library. Once you select the component using something like `findComponent(".some-selector")` what do you do? Are you then accessing `.vm`?

**Comment by afontcu** [comment]
I also agree we should not support using CSS selectors and encourage terser ones instead where possible. Moreover, `findComponent` on v1 only search for `Component|ref|name`, not CSS selectors

**Comment by Giwayume** [comment]
I think maybe I'm digging into the weeds too much, I don't care so much what `findComponent` or `findAllComponents` specifically does so long as I still have a solution in V2 to use a query selector to get to a `Wrapper<Vue>`.

```
const vueComponentEl: Element | null = wrapper.element.querySelector('.some-selector')`;
const vueComponentWrapper: Wrapper<Vue> = `WHAT GOES HERE?`;
```
