### ISSUE TITLE
more util functions can be exported ?

### ISSUE THREAD

**Issue by danranVm** [vuejs/vue-test-utils-next#726]
like: `isElementVisible`, `createDOMEvent` etc...

**Comment by lmiller1990** [comment]
We can, but it'd be nice to know what your use case is before we do. What do you have in mind?

**Comment by danranVm** [comment]
@lmiller1990  oh, sorry, I almost forgot this issue.

In some cases, when we cannot get DOMwrapper directly, we need to use these utils functions to help us complete the test.

```ts
test('test', async () => {
  const wrapper = mount({
    template: `<teleport to="ix-modal-container"><div class="ix-modal" /></teleport>`,
    attachTo: 'body',
  })

  expect(isElementVisible(document.querySelector('.ix-modal'))).toBe(true)
})
```

**Comment by lmiller1990** [comment]
In that particular case, you could use the `isVisible` assertion from `testing-library/jest-dom`. We got the code from there: https://github.com/vuejs/vue-test-utils-next/blob/master/src/utils/isElementVisible.ts#L3

But we could expose this.

Any use for `createDOMEvent` though? I'd rather expose functions one by one, if they need to be, rather than just exposing everything for the sake of it.

**Comment by lmiller1990** [comment]
Happy to re-open if there is more activity. I don't see any action to take right now, so I'll close this.
