### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by DominicGBauer** [vuejs/vue-test-utils-next#748]
Hi guys

Thanks for this plugin it's really epic. 

I wanted to contribute a doc change as there's a link that's incorrect but seem to get this error `ERROR: Permission to vuejs/vue-test-utils-next.git denied to DominicGBauer.`

I was wondering if contributing was allowed or if I'm just missing something?

**Comment by lmiller1990** [comment]
Hi!

Yes, contributions are always welcome. Due to how many people use and depend on this repo, not just anyone can push a branch here.

What you'll need to do is fork this repo, make your change, and make a pull request. The easiest way to do this would be go find the file you want to change, click "edit", and GitHub should automatically fork it for you.

![image](https://user-images.githubusercontent.com/19196536/125244353-93a70a80-e332-11eb-82de-d45f64ff649c.png)

Give that a try, ping me if you still cannot figure it out.

**Comment by DominicGBauer** [comment]
@lmiller1990 epic thanks for getting back to me made a PR here https://github.com/vuejs/vue-test-utils-next/pull/776 and will close this!
