### ISSUE TITLE
DOMWrapper support styles like classes 

### ISSUE THREAD

**Issue by danranVm** [vuejs/vue-test-utils-next#754]
The simplest usage.

```ts
const wrapper = mount({ template: `<div style="position: absolute;">` })

expect(wrapper.styles().position).toBe('absolute')

// expect(wrapper.find('selector').styles().position).toBe('absolute')
```

Or is there a better way?

**Comment by nandi95** [comment]
This can already be done with
`expect(wrapper.attributes('style')).toContain('position: absolute')`

However this isn't a bad idea for the sake of consistency as there is a `classes` method that either returns an array of classes or a boolean if string argument given. Perhaps similar thing could be added except it returns a object with keys being the rule the values the value.

Like above and:
`expect(wrapper.styles('position')).toBe('absolute')`

**Comment by cexbrayat** [comment]
Maybe `expect(wrapper.element.style.position).toBe('absolute')` would work as well?

If either @nandi95 `wrapper.attributes('style')` or my example above works, I'm not sure we should add more things to the API.

**Comment by lmiller1990** [comment]
We had something similar, `hasStyle`, and I think we also had `styles` a long time ago... I found [this issue](https://github.com/vuejs/vue-test-utils/issues/330).

I am fairly sure this was removed due to complexity - `styles` needs to consider a lot of things, like `element.style`, computed styles, etc. Also, people often do:

```
<div class="blah" />

<style>
.blah { position: absolute; }
</style>
```

Then expect `styles('position')` to contain `absolute`, which is won't. 

I think the bet way to do this is `wrapper.element.style.position` (fairly sure that should work).

**Comment by danranVm** [comment]
Sorry, I didn’t know that I could do it like `wrapper.element.style.position`, I just tried it and it works great.

But, I got a Typescript type error:  `Property 'style' does not exist on type 'Element'`,  Is there any good way to solve it? the way I can think of is  :  ` (wrapper.element as HTMLElement).style.position`

**Comment by cexbrayat** [comment]
Yes, that looks good 👍
`wrapper.get('div').element` is smart enough to be `HTMLDivElement`, but `wrapper.element` must probably be explicitly cast as you did.

**Comment by lmiller1990** [comment]
`find` and `get` are generic, you can also do `wrapper.get<HTMLSpanElement>('.blah')` and it will infer the type is `SPAN`, etc.
