### ISSUE TITLE
How to test teleport, if subcomponents not a vue component

### ISSUE THREAD

**Issue by Yijx** [vuejs/vue-test-utils-next#798]
I have a vue component like this
```
<template>
  <teleport to="body">
     <div class="hello">
    </div>
  </teleport>
</template>
```
It is different from https://next.vue-test-utils.vuejs.org/guide/advanced/teleport.html
I can use document.body.querySelect('.hello'), it is work.
but wrapper.find or wrapper.findComponent, they are not work.
so, how can i test this component, it is a same question in stackoverflow https://stackoverflow.com/questions/66923194/how-to-make-vue3-test-utils-work-with-teleport

**Comment by lmiller1990** [comment]
Good question, I posted some of my ideas on that SO thread: https://stackoverflow.com/questions/66923194/how-to-make-vue3-test-utils-work-with-teleport/68552979#68552979

I don't have a great solution right now. You could make an assertion against the `document.body`, that should work. It's not the cleanest solution, though.

I'll think about this a bit more and try to add something to Test Utils to handle this scenario. Do you have any ideas?

**Comment by dospunk** [comment]
I have a similar issue right now, I'm trying to test a component using [headlessui](https://github.com/tailwindlabs/headlessui/tree/main/packages/%40headlessui-vue)'s Dialog component which uses Teleport, but Dialog does not expose its target, so there is no way to manually create a target for it as suggested in the docs

**Comment by lmiller1990** [comment]
I tried to find a solution for teleport and headlessui. They hav some tests, which are kind of complex but worth looking at: https://github.com/tailwindlabs/headlessui/blob/d25f80ae9d896446c2b7119a70cfd5d99e250050/packages/%40headlessui-vue/src/components/dialog/dialog.ts#L98

Due to how they manage the `<teleport>` internally, I think we need to use `attachTo` and query `document`, no `wrapper.html()`.

Here's a quick example:

```ts
  it.only('works with headlessui', async () => {
    // @ts-ignore
    window.IntersectionObserver = class {
    // @ts-ignore
      observe () {}
    }
    const Comp = defineComponent({
      components: { Dialog, DialogOverlay, DialogTitle, PortalGroup },
      template: `
        <button @click="isOpen = true">Open</button>
        <Dialog :open="isOpen" @close="close" to="#id">
          <DialogTitle>Dialog title</DialogTitle>
          <DialogOverlay />
          <input />
        </Dialog>
      `,
      setup () {
        const isOpen = ref(true)
        return {
          isOpen,
          close: () => isOpen.value = false
        }
      }
    })
    const destination = document.createElement('div')
    destination.id = 'somewhere'
    document.body.appendChild(destination)

    const wrapper = mount(Comp, {
      attachTo: destination
    })
    console.log(wrapper.html())
    console.log(document.body.outerHTML)
    await wrapper.find('button').trigger('click')
  })
```

This logs:

```
<body><div id="somewhere"><div data-v-app=""><button>Open</button><!--teleport start--><!--teleport end--></div></div><div id="headlessui-portal-root"><div><div to="#id" id="headlessui-dialog-1" role="dialog" aria-modal="true"><h2 id="headlessui-dialog-title-2">Dialog title</h2><div id="headlessui-dialog-overlay-3" aria-hidden="true"></div><input></div></div></div></body>
```

So the content is there.

See [this doc](https://next.vue-test-utils.vuejs.org/guide/advanced/teleport.html) or [this video](https://www.youtube.com/watch?v=bhYtFWDgJmY) for some ideas on how you can continue using the VTU wrapper API.

This solution is kind of complex and hard to understand, I would like something a bit more ergonomic, but I'm not sure what. I think a utility function could probably abstract away a lot of this complexity.

**Comment by AndreasNasman** [comment]
Hi!

I'm writing a similar test to the one described [in the teleport docs](https://next.vue-test-utils.vuejs.org/guide/advanced/teleport.html) and the [accompanying video](https://www.youtube.com/watch?v=bhYtFWDgJmY), but with a slight variation.

The child component which I need to test (and causing the issue) is a [Dialog component](https://www.primefaces.org/primevue/showcase/#/dialog) from PrimeVue.

```vue
<template>
  <h5>Parent</h5>
  <Dialog :visible="true">
    ...
  </Dialog>
</template
...
```

Looking at the [Dialog's source code](https://github.com/primefaces/primevue/blob/master/src/components/dialog/Dialog.vue#L2), I noticed that the **component itself** uses the built-in `<Teleport>` component, which causes some unexpected behavior for me. This differs from the documentation where the `<Teleport>` component is in the parent.

I'm able to correctly locate the Dialog component using `getComponent`/`findComponent` as you @lmiller1990 described in the docs and video,

```js
const dialog = parent.getComponent(Dialog);
```

 but invoking e.g. `get` on it

```js
const input = dialog.get('input');
```

 fails. The reason seems to be that `get` still searches in the context of the parent – the `parent` component in my example – although the context should be the `dialog` component, at least to my understanding.

Running `html()` on the Dialog component verifies the context still being the parent:

```js
console.log('parent\n', parent.html());
console.log('dialog\n', dialog.html());

// ...
// console.log tests/unit/DialogTest.spec.ts:27
//   parent
//    <h5>Parent</h5>
//   <!--teleport start-->
//   <!--teleport end-->
// 
// console.log tests/unit/DialogTest.spec.ts:28
//   dialog
//    <h5>Parent</h5>
//   <!--teleport start-->
//   <!--teleport end-->
// ...
```

In the actual test, I have a button that opens the dialog and an input field I want to modify, but that should be irrelevant for this issue.

---

I was able to replicate this with some minimal changes to [`Navbar.vue`](https://github.com/lmiller1990/vuejs-composition-api-course/blob/main/src/components/Navbar.vue) and [its test file](https://github.com/lmiller1990/vuejs-composition-api-course/blob/main/tests/unit/Navbar.spec.ts) in the [vuejs-composition-api-course](https://github.com/lmiller1990/vuejs-composition-api-course) project. I basically moved the `<teleport to="#modal">` part to the `Signup` component itself to replicate the problem (attaching a `.patch` file with the changes).
[0001-Make-breaking-changes.patch.zip](https://github.com/vuejs/vue-test-utils-next/files/7512434/0001-Make-breaking-changes.patch.zip)


---

Is there some concept I'm missing or some modifications I need to make to adapt to the child containing `<Teleport>`? Or, could there be a bug with contexts when using `get/findComponent` for components using `teleport`?

Hopefully, I came across somewhat clear! 😄

– Andreas

**Comment by AndreasNasman** [comment]
Any comments on this @lmiller1990?

**Comment by TheDutchCoder** [comment]
I wonder if we could stub out the teleport all together?
I don't see a real purpose for it in testing anyway, because it just moves pieces of the DOM around.

Would that be an option?

**Comment by lmiller1990** [comment]
We could definitely stub out `<teleport>` - we do that what with `Transition`. We have that logic [here](https://github.com/vuejs/vue-test-utils-next/blob/master/src/stubs.ts#L164), you'd just need to copy-paste it for `<teleport>`. I'm not sure if we want to default to this or not, but we could definitely add

```ts
mount(Foo, {
  global: {
    stubs: {
      teleport: true
    }
  }
})
```

Would someone like to make this PR? I could do it otherwise, but I'd really like to grow the contributors to this repo, since it's only a few people right now. This should be quite easy, since we have the concept already for transitions.

**Comment by TheDutchCoder** [comment]
I'll see if I can clone the repo and maybe PR this!

**Comment by lmiller1990** [comment]
Added some review comments 👍

**Comment by lmiller1990** [comment]
@AndreasNasman  @Yijx we released rc.17, which has support for stubbing teleport: https://github.com/vuejs/vue-test-utils-next/releases/tag/v2.0.0-rc.17

```ts
mount(Comp, {
  global: {
    stubs: {
      teleport: true
    }
  }
})
```

This might be useful? Just stub `teleport`, and hopefully business as usual. I didn't test this on the reproduction you posted yet @AndreasNasman, but let me know if this helps.

**Comment by AndreasNasman** [comment]
Thanks, great work! 🥳
I'll test it later today and let you know how it went! 👍

**Comment by AndreasNasman** [comment]
Works perfectly for our needs, thank you! 🙏

**Comment by dospunk** [comment]
This is a good solution, though I just wanted to chime in and say it doesn't work for headlessui. I suspect this is a headlessui problem though, not a VTU problem. For some reason the Dialog's FocusTrap can't find the contents of the Dialog when teleport is stubbed out causing an infinite loop? I don't really get it. Anyway, this is just for anyone else in the future running across this issue who's having the same issues with headlessui that I did.

**Comment by d0peCode** [comment]
How to use same solution (stubs) if I have my teleport like this:

```
<component :is="teleport" to="body">
```

I must do teleport like this because of vite building issue: https://github.com/vuejs/core/issues/2855#issuecomment-768388962

**Comment by lmiller1990** [comment]
What is your testing stack? Is this Vitest specific?

What is the goal - to avoid teleporting your content from your component? Eg, can you share your entire test and intention?

**Comment by Made-of-Clay** [comment]
Stubbing teleport works great - thanks so much!

**Comment by Made-of-Clay** [comment]
5 days in and I'm finding the stubbed teleport isn't reactive 😕 Maybe I'm missing something.

**Comment by lmiller1990** [comment]
> 5 days in and I'm finding the stubbed teleport isn't reactive 😕 Maybe I'm missing something.

I'm not sure if the current state of this library lends itself well to testing teleport in general - I wonder if we need better docs, a better/new API for this, or something else.

Can you share a minimal reproduction?

I am not exactly what you mean, but I wouldn't expected a stubbed component to do much at all.

**Comment by lmiller1990** [comment]
Ah sorry, for reproductions, people often use https://stackblitz.com/edit/vitest-dev-vitest-2cimwj?file=test/basic.test.ts (ready to go). Or you can fork this repo and add a test case.

I will make a new issue for this.

**Comment by lmiller1990** [comment]
https://github.com/vuejs/test-utils/issues/2033

**Comment by lmiller1990** [comment]
@Made-of-Clay would you be interested in trying to fix this? You could add a test case to this test suite, and try to fix it. The stubbing stuff for Teleport is here: https://github.com/vuejs/test-utils/blob/main/src/vnodeTransformers/stubComponentsTransformer.ts#L123-L127

**Comment by vincerubinetti** [comment]
Hi all. 

I was using the teleport stub solution mentioned above previously, with test utils version `2.0.2`. Upgrading to the latest version, `2.3.2`, it breaks. I have a dropdown component where the dropdown is teleported to `body`, and with the latest version, inspecting the wrapper HTML, there is no dropdown there.

Could someone consider looking into this or re-opening this issue as a possible regression? I'm assuming since it's the same major version there wouldn't be any breaking changes with this particular functionality.

**Comment by lmiller1990** [comment]
Can you try previous versions (maybe 2.3.1, 2.3.0) and isolate the issue?

How about making a new one describing the version with the breakage? I think it's better to track a new regression in a new issue. Thanks!

**Comment by dpogue** [comment]
> Can you try previous versions (maybe 2.3.1, 2.3.0) and isolate the issue?
> 
> How about making a new one describing the version with the breakage? I think it's better to track a new regression in a new issue. Thanks!

This sounds like the same issue I'm facing, where the behaviour of subbing teleport broke in 2.2.0.

**Comment by lmiller1990** [comment]
Oh, so this one would be the issue to follow: https://github.com/vuejs/test-utils/issues/2033
