### ISSUE TITLE
Docs: trigger custom event

### ISSUE THREAD

**Issue by scvnc** [vuejs/vue-test-utils-next#885]
As a Vue3 newbie, coming from React land.  I wanted to trigger a custom event and assumed I could do something like `wrapper.trigger('my-custom-event')`

It seems this does not work for custom events and is only for DOM events.  Digging a bit I see that others have accomplished this with `wrapper.vm.$emit`

- Is this the correct way to test custom events?  Would testing a custom event be an antipattern in design or testing? 

  - describe `<component-under-test>`
      - describe when custom event is emitted from `<child-component>` 
          - it should call another service with expected parameters

- Should we make a footnote on the docs to suggest this method? `wrapper.vm.$emit`
- Would it be useful to have `wrapper.triggerCustom('my-custom-event')` as a convenience method of sorts?
   - bonus: could this method observe the `emits: ['my-custom-event']` property on the component somehow and error if the custom event is not defined?

**Comment by lmiller1990** [comment]
Here's an example PR showing how I'd generally approach this kind of test. It is using the new [script setup](https://v3.vuejs.org/api/sfc-script-setup.html) syntactic sugar. It allows for improved type safety with `defineEmits` and `defineProps`.

https://github.com/vuejs/vue-test-utils-next/compare/issue-885-example?expand=1

While it is possible to pass a callback as a prop in Vue, a more common approach is to respond to an event. I showed that in my above example - you can use `emitted` if you really would like to see the internally emitted events. Generally, I'd recommend against tests like "it calls the XXX prop" - this is an implementation detail. What you really want to test is what happens when XXX prop is called - in this scenario, the delete service is called with the correct argument. The same thing applies in React - I'd write this test with the same ideas and assertions  for React using Testing Library.

> ... it does seem tricky if your testing library isn't aware of the view framework internals ...

Ideally, a framework should *not* be aware of internals. It's tricky because generally internals aren't exposd - they are internals, after all. While Enzyme supported this, a lot of those code bases did not age well and the test suites were very brittle. Testing implementation details is generally a not a good idea. Those test are brittle and are likely to break during a refactor. This is the reason libraries like Testing Library don't expose the underlying internals.

Re: type safety

You might see I had to `ts-ignore` a bit - unless you are using TSX (which is very possible, we have some simple [examples](https://github.com/vuejs/vue-test-utils-next/blob/master/tests/features/with-tsx.spec.tsx) but you can google more on how to configure TSX) you won't get the same level of completion as React when importing a `vue` file, at least not yet. A lot of work is getting done using the VS Code extension Volar to support this, though.

**Comment by julisch94** [comment]
I have come across the same issue and found this conversation.

I wanted to trigger a custom event `change` with the string `foo` but 
```ts
myComponent.trigger('change', 'foo')
```
yields this:
```
event triggered! value: Event {
  '0': 'f',
  '1': 'o',
  '2': 'o',
  isTrusted: [Getter],
  _vts: 1714118428122
}
```
which is unacceptable.

A workaround for now is:
```ts
myComponent.vm.$emit('change', 'foo')
```
which yields as expected:
```
event triggered! value: foo
```
